export enum TabScreens {
  LOANS = 'Loans',
  DEPOSITS = 'Deposits',
  DASHBOARD = 'Dashboard',
  NOTIFICATIONS = 'Notifications',
  MORE = 'More',
}

export enum Routes {
  FAQ = '/FAQ',
  ONBOARDING = '/',
  SIGN_IN = '/sign-in',
  PROFILE = '/profile',
  SIGN_UP = '/sign-up',
  PAYMENTS = '/payments',
  CARD_MENU = '/card-menu',
  STATISTICS = '/statistics',
  IBAN_PAYMENT = '/iban-payment',
  INVOICE_SENT = '/invoice-sent',
  NEW_PASSWORD = '/new-password',
  OPEN_DEPOSIT = '/open-deposit',
  CARD_DETAILS = '/card-details',
  FUND_TRANSFER = '/fund-transfer',
  OPEN_NEW_LOAN = '/open-new-loan',
  OPEN_MONEYBOX = '/open-moneybox',
  TAB_NAVIGATOR = '/tab-navigator',
  OPEN_NEW_CARD = '/open-new-card',
  CREATE_INVOICE = '/create-invoice',
  MOBILE_PAYMENT = '/mobile-payment',
  PAYMENT_FAILED = '/payment-failed',
  TOP_UP_PAYMENT = '/top-up-payment',
  PRIVACY_POLICY = '/privacy-policy',
  FORGOT_PASSWORD = '/forgot-password',
  CHANGE_PIN_CODE = '/change-pin-code',
  PAYMENT_SUCCESS = '/payment-success',
  VERIFY_YOUR_EMAIL = '/verify-your-email',
  CONFIRMATION_CODE = '/confirmation-code',
  EDIT_PERSONAL_INFO = '/edit-personal-info',
  TRANSACTION_DETAILS = '/transaction-details',
  SIGN_UP_ACCOUNT_CREATED = '/sign-up-account-created',
  VERIFY_YOUR_PHONE_NUMBER = '/verify-your-phone-number',
  FORGOT_PASSWORD_SENT_EMAIL = '/forgot-password-sent-email',
}
